/**:
  ros__parameters:
    rate: 200
    x0: 0.0
    y0: 0.0
    theta0: 0.0
    arena_x_length: 4.0
    arena_y_length: 4.0
    obstacles/x: [ -0.5, 0.8, 0.8]
    obstacles/y: [ -0.7, -0.8, 0.8]

    obstacles/radius: 0.03
   